import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "ادمین",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "مهدی",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "تیشرت آزاد",
      slug: "free-shirt",
      category: "تیشرت",
      image: "/images/shirt1.jpg",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      price: 70,
      brand: "نایک",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "تیشرت راحت و پر طرفدار",
    },
    {
      name: "تیشرت فیت",
      slug: "fit-shirt",
      category: "تیشرت",
      image: "/images/shirt2.jpg",
      isFeatured: true,
      featuredImage: "/images/banner2.jpg",
      price: 80,
      brand: "ادیداس",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "تیشرت مناسب و پر طرفدار",
    },
    {
      name: "اسلیم شرت",
      slug: "slim-shirt",
      category: "تیشرت",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "ریموند",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "تیشرت و پر طرفدار",
    },
    {
      name: "شلوار گلف",
      slug: "golf-pants",
      category: "شلوار",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "الیور",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "شلوار هوشمندانه",
    },
    {
      name: "شلوار فیت",
      slug: "fit-pants",
      category: "شلوار",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "زارا",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "شلوار پرطرفدار",
    },
    {
      name: "شلوار کلاسیک",
      slug: "classic-pants",
      category: "شلوار",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "کسلی",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "شلوار مناسب میهمانی",
    },
    {
      name: "پیراهن شلواری",
      slug: "shirt-trousers",
      category: "پیراهن",
      image: "/images/outfit1.jpg",
      featuredImage: "/images/banner1.jpg",
      isFeatured: true,
      price: 150,
      brand: "Zara",
      rating: 4.2,
      numReviews: 8,
      countInStock: 5,
      description: "پیراهن شلواری با طرح مدرن و مناسب برای مراسم های رسمی",
    },
    {
      name: "کیف دستی",
      slug: "handbag",
      category: "کیف و کفش",
      image: "/images/handbag1.jpg",
      isFeatured: false,
      price: 80,
      brand: "H&M",
      rating: 3.9,
      numReviews: 12,
      countInStock: 2,
      description: "کیف دستی با طرح جذاب و مناسب برای مهمانی ها و مجالس",
    },
    {
      name: "سوئیشرت زمستانی",
      slug: "winter-sweater",
      category: "سویشرت",
      image: "/images/sweater1.jpg",
      isFeatured: true,
      price: 100,
      brand: "Gap",
      rating: 4.6,
      numReviews: 18,
      countInStock: 0,
      description: "سوئیشرت زمستانی با طراحی شیک و جذاب و با کیفیت بالا",
    },
  ],
};
export default data;
